# Copyright (C) 2021 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for LingTiGameAcc
LUCI_DEPENDS:=+LingTiGameAcc
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-LingTiGameAcc
PKG_VERSION:=1.0
PKG_RELEASE:=1.7.6

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
