#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

NAME="LingTiGameAcc"
lingti_BIN="/usr/share/LingTiGameAcc/lingti"
lingti_CONF="/usr/share/LingTiGameAcc/lingti.conf"
lingti_LOGFILE="/tmp/LingTiGameAcc.log"

start_service() {
  config_load lingti
	local enable
	config_get_bool enable lingti enabled
	if [ "$enable" -eq 1 ]; then
    procd_open_instance
    procd_set_param command $lingti_BIN $lingti_CONF >$lingti_LOGFILE 2>&1
    procd_set_param respawn
    procd_close_instance
	fi
}

